config/routes.rb
require 'resque/server'

Frontend::Application.routes.draw do
  mount Api => '/api'

  root 'home#index'

  get '/admin',   to: redirect('pcadmin/home')
  get '/pcadmin', to: redirect('pcadmin/home')
  match '/admin/:name', to: redirect("pcadmin/%{name}"), via: [:get, :post]

  namespace :pcadmin, module: :admin, as: :admin do

    root 'home#index'

    match '/widgets/update_widget_area' => 'widgets#update_widget_area', via: [:get]
    match '/categories/change_status' => 'categories#change_status', via: [:get]
    match '/coupons/change_status' => 'coupons#change_status', via: [:get]
    match '/shops/change_status' => 'shops#change_status', via: [:get]
    match '/shops/order_coupons' => 'shops#order_coupons', via: [:get]
    match '/shops/update_coupon_order' => 'shops#update_coupon_order', via: [:get]
    match '/shops/import_template' => 'shops#import_template', via: [:get]
    match '/coupons/import_template' => 'coupons#import_template', via: [:get]
    match '/campaigns/import_template' => 'campaigns#import_template', via: [:get]
    match '/tags/import_template' => 'tags#import_template', via: [:get]
    match '/shops/update_shop_list_priority' => 'shops#update_shop_list_priority', via: [:post]
    match '/templates/save' => 'templates#save', via: [:post]
    match '/templates/get_layout' => 'templates#get_layout', via: [:get]
    match '/templates/restore_default' => 'templates#restore_default', via: [:get]
    match '/templates/delete_layout' => 'templates#delete_layout', via: [:delete]
    match '/caches' => 'caches#purge_url', via: [:post]
    match '/awin' => 'awin_migration#awin', via: [:get]
    match '/reload_routes' => 'settings#reload_routes', via: [:get]
    match '/migrate_awin' => 'awin_migration#migrate_awin', via: [:post]
    match '/shops/render_shops_select' => 'shops#render_shops_select', via: [:get]

    devise_for :users, class_name: 'User', controllers: {
      passwords:     'admin/passwords',
      registrations: 'admin/registrations',
      sessions:      'admin/sessions'
    }

    scope :users, as: :users do
      devise_scope :admin_user do
        post 'pre_sign_in', to: 'sessions#pre_sign_in'
      end
      resource :two_factors, only: [:create, :destroy], controller: 'users/two_factors'
    end

    authenticate do
      mount Resque::Server, :at => "/tasks"
    end

    resources :affiliate_networks, only: [:index, :new, :edit, :create, :update]

    resources :alerts, only: [:index, :destroy, :edit] do
      member do
        post 'mark_solved', to: 'alerts#mark_solved'
      end
    end

    resources :authors, only: [:index, :new, :edit, :create, :update]

    resources :banners

    resources :caches, only: [:index]

    resources :campaigns, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :campaign_imports

    resources :categories, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'order'
        post 'order', to: 'categories#update_order'
      end
    end

    resources :countries, only: [:index, :new, :edit, :create, :update]

    resources :coupons, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
      member do
        get 'coupon_codes', to: 'coupons#coupon_codes'
      end
    end

    resources :coupon_codes, only: [:index, :new, :edit, :create, :update, :import] do
      collection do
        get 'approve_imported'
        get 'remove_imported'
        get 'export_modal'
        get 'export'
      end
    end

    resources :coupon_imports

    resources :coupon_code_imports, only: [:new, :create]

    resources :csv_exports, only: [:index, :edit, :destroy] do
      member do
        get 'rerun'
      end
    end

    resources :globals do
      collection do
        get 'export_modal'
        get 'export'
        get 'shop_mappings'
        post 'update_shop_mapping'
      end
    end

    resources :home, only: [:index]

    resources :media, only: [:index, :new, :edit, :create, :update]

    resources :options

    scope :quality do
      get 'active_coupons', to: 'quality#active_coupons'
      get 'http_links', to: 'quality#http_links'
      get 'invalid_urls', to: 'quality#invalid_urls'

      resources :expired_exclusives, only: [:index, :edit] do
        collection do
          get 'edit', to: 'expired_exclusives#edit', as: 'bulk_edit'
          post 'update', to: 'expired_exclusives#update', as: 'update'
        end
      end
    end

    resources :redirect_rules

    resources :settings, only: [:index, :update]

    patch :image_settings, to: 'settings#update_image_settings', as: :image_settings

    resources :shop_imports

    resources :shops, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
        get 'synch_keywords'
      end
    end

    resources :sites, only: [:index, :new, :edit, :create, :update]

    resources :snippets, only: [:index, :new, :edit, :create, :update]

    resources :static_pages, only: [:index, :new, :edit, :create, :update]

    resources :tags do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :tag_imports

    resources :templates, only: [:index]

    resources :tracking_clicks

    resources :tracking_users

    resources :translations do
      collection do
        get 'export_keys'
      end
    end

    resources :widgets

    resources :users, only: [:index, :new, :edit, :create, :update] do
      get '/current_site_id/:site_id', to: 'users#set_current_site_id'  , as: 'site_id'
      get '/unset_current_site_id'   , to: 'users#unset_current_site_id', as: 'unset_site_id'
    end
  end

  get '/index.php',       to: redirect('/')
  get '/index.php/*path', to: redirect{|params, request| "/#{params[:path]}#{ '.'+params[:format] if params[:format].present? }"}

  # FRONTEND ROUTES ARE LOADED DYNAMICALLY

  # DynamicRoutes.load_static_redirects

  DynamicRoutes.load

  # This is a fallback if no route can be matched and if not even the frontend controller is triggered to forward to a 404 page
  match "*path", to: "frontend#not_found", via: :all
  post "/", to: "frontend#not_found"
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :coupons
  has_many :categories
  has_many :shops
  has_many :tags

  has_many :sites
  has_many :site_users, through: :sites, source: :users

  has_many :user_countries
  has_many :country_users, through: :user_countries, foreign_key: :country_id, source: :user

  validates_presence_of :name, :locale
  validates_uniqueness_of :name

  after_save :assign_to_super_user

  def self.grid_filter(params)
    query = self
    query = query.where('1=1')
    query = query.where(id: params[:id]) if params[:id].present?
    query = query.where('name like ?', "%#{params[:name]}%") if params[:name].present?
    query = query.where('locale like ?', "%#{params[:locale]}%") if params[:locale].present?
    query
  end

  def self.cultures
    %w[
      af ar at az bg bn bs ca cs cy da de de_AT de_CH el en en_AU en_CA en_GB en_IE en_IN en_NZ en_US eo es es_ES es_419
      es_AR es_CL es_CO es_CR es_MX es_PA es_PE es_VE et eu fa fi fr fr_CA fr_CH gl he hi hi_IN hr hu id is it it_CH ja
      kn ko lo lt lv mk mn ms nb ne nl nn or pl pt pt_BR rm ro ru sk sl sr sv sw th tl tr uk ur uz vi wo zh_CN zh_HK zh_TW
    ]
  end

  def users
    (site_users + country_users).uniq
  end

  def user_ids
    users.map(&:id).uniq
  end

  private
    def assign_to_super_user
      SuperUser.all.each do |su|
        UserCountry.find_or_create_by(country_id: self.id, user_id: su.id)
      end
    end
end

app/controllers/admin/countries_controller.rb
require 'vue_data/country'

module Admin
  class CountriesController < BaseController
    before_action :authenticate_admin_user!
    load_and_authorize_resource

    before_action :set_country, only: [:edit, :update]

    # GET /admin/countries
    # GET /admin/countries.json
    def index
      respond_to do |format|
        format.json { render json: VueData::Country.render_json(nil, params), status: :ok }
        format.html
      end
    end

    # GET /admin/countries/new
    def new
      @country = Country.new
    end

    # GET /admin/countries/1/edit
    def edit
    end

    # POST /admin/countries
    # POST /admin/countries.json
    def create
      @country = Country.new(country_params)

      respond_to do |format|
        if @country.save
          format.html { redirect_to admin_countries_url, notice: 'Country was successfully created.' }
          format.json { render action: 'show', status: :created, location: @country }
        else
          format.html { render action: 'new' }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/countries/1
    # PATCH/PUT /admin/countries/1.json
    def update
      respond_to do |format|
        if @country.update(country_params)
          format.html { redirect_to admin_countries_url, notice: 'Country was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_country
        # @country = Country.find(params[:id])
        @country = Country.find(params[:id]) || not_found
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def country_params
        params.require(:country).permit(:name, :locale)
      end
  end
end

app/views/admin/countries/_form.html.erb
  <div class="col-sm-12">

    <div class="box bordered-box blue-border">

      <div class="box-header blue-background">

        <div class="title">

          <i class="icon-edit"></i>

          Country Form

        </div>

      </div>

      <div class="box-content">

        <%= form_for [:admin, @country], html: {class: 'form form-horizontal', style: 'margin-bottom: 0'} do |f| %>

        <%= render partial: 'admin/shared/form_errors', locals: {ancestor: @country} %>

        <div class="form-group <%= 'has-error' unless @country.errors.messages[:name].blank? %>">

          <%= f.label :name, class: 'col-md-2 control-label' %>

          <div class="col-md-5">

            <%= f.text_field :name, class: 'form-control' %>

          </div>

        </div>

        <div class="form-group <%= 'has-error' unless @country.errors.messages[:locale].blank? %>">

          <%= f.label :locale, class: 'col-md-2 control-label' %>

          <div class="col-md-5">

            <%= f.select :locale, I18n.available_locales, {include_blank: true}, class: 'form-control' %>

          </div>

        </div>

        <div class="form-actions form-actions-padding-sm">

          <div class="row">

            <div class="col-md-10 col-md-offset-2">

              <%= f.submit nil, class: 'btn btn-primary' if can? :create, Country %>

              <%= link_to t('.cancel', default: t('helpers.links.cancel')), admin_countries_path, class: 'btn' %>

            </div>

          </div>

        </div>

        <% end %>

      </div>

    </div>

  </div>

app/views/admin/countries/edit.html.erb
<% model_class = Country %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-globe"></i>

        <span><%= t '.title', default: 'Edit %{model}', model: model_class.model_name.human.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li><%= model_class.model_name.human.pluralize.titleize %></li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active">Edit</li>

        </ul>

      </div>

    </div>

  </div>

</div>

<div class="row">

  <%= render partial: 'admin/shared/flash' %>

</div>

<div class="row">

  <%= render partial: 'form' %>

</div>

<div class="row">

app/views/admin/countries/index.html.erb
<% model_class = Country %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-globe"></i>

        <span><%= t '.title', default: model_class.model_name.human.pluralize.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li><%= model_class.model_name.human.pluralize.titleize %></li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active"><%= model_class.model_name.human.pluralize.titleize %></li>

        </ul>

      </div>

    </div>

  </div>

</div>

<%= render :partial => 'admin/shared/flash' %>

<div class="box">

  <div class="box-content">

    <% if can? :create, model_class %>

      <div class="btn-toolbar">

        <%= link_to '<i class="icon-plus"></i> New Country'.html_safe, new_admin_country_path, class: 'btn btn-success' %>

      </div>

    <% end %>

    <div class="table-responsive">
      <div id="app"></div>
    </div>

  </div>

</div>

app/views/admin/countries/new.html.erb
<% model_class = Country %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-globe"></i>

        <span><%= t '.title', default: 'New %{model}', model: model_class.model_name.human.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li><%= model_class.model_name.human.pluralize.titleize %></li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active">New</li>

        </ul>

      </div>

    </div>

  </div>

</div>

<div class="row">

  <%= render partial: 'admin/shared/flash' %>

</div>

<div class="row">

  <%= render partial: 'form' %>

</div>