config/routes.rb
require 'resque/server'

Frontend::Application.routes.draw do
  mount Api => '/api'

  root 'home#index'

  get '/admin',   to: redirect('pcadmin/home')
  get '/pcadmin', to: redirect('pcadmin/home')
  match '/admin/:name', to: redirect("pcadmin/%{name}"), via: [:get, :post]

  namespace :pcadmin, module: :admin, as: :admin do

    root 'home#index'

    match '/widgets/update_widget_area' => 'widgets#update_widget_area', via: [:get]
    match '/categories/change_status' => 'categories#change_status', via: [:get]
    match '/coupons/change_status' => 'coupons#change_status', via: [:get]
    match '/shops/change_status' => 'shops#change_status', via: [:get]
    match '/shops/order_coupons' => 'shops#order_coupons', via: [:get]
    match '/shops/update_coupon_order' => 'shops#update_coupon_order', via: [:get]
    match '/shops/import_template' => 'shops#import_template', via: [:get]
    match '/coupons/import_template' => 'coupons#import_template', via: [:get]
    match '/campaigns/import_template' => 'campaigns#import_template', via: [:get]
    match '/tags/import_template' => 'tags#import_template', via: [:get]
    match '/shops/update_shop_list_priority' => 'shops#update_shop_list_priority', via: [:post]
    match '/templates/save' => 'templates#save', via: [:post]
    match '/templates/get_layout' => 'templates#get_layout', via: [:get]
    match '/templates/restore_default' => 'templates#restore_default', via: [:get]
    match '/templates/delete_layout' => 'templates#delete_layout', via: [:delete]
    match '/caches' => 'caches#purge_url', via: [:post]
    match '/awin' => 'awin_migration#awin', via: [:get]
    match '/reload_routes' => 'settings#reload_routes', via: [:get]
    match '/migrate_awin' => 'awin_migration#migrate_awin', via: [:post]
    match '/shops/render_shops_select' => 'shops#render_shops_select', via: [:get]

    devise_for :users, class_name: 'User', controllers: {
      passwords:     'admin/passwords',
      registrations: 'admin/registrations',
      sessions:      'admin/sessions'
    }

    scope :users, as: :users do
      devise_scope :admin_user do
        post 'pre_sign_in', to: 'sessions#pre_sign_in'
      end
      resource :two_factors, only: [:create, :destroy], controller: 'users/two_factors'
    end

    authenticate do
      mount Resque::Server, :at => "/tasks"
    end

    resources :affiliate_networks, only: [:index, :new, :edit, :create, :update]

    resources :alerts, only: [:index, :destroy, :edit] do
      member do
        post 'mark_solved', to: 'alerts#mark_solved'
      end
    end

    resources :authors, only: [:index, :new, :edit, :create, :update]

    resources :banners

    resources :caches, only: [:index]

    resources :campaigns, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :campaign_imports

    resources :categories, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'order'
        post 'order', to: 'categories#update_order'
      end
    end

    resources :countries, only: [:index, :new, :edit, :create, :update]

    resources :coupons, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
      member do
        get 'coupon_codes', to: 'coupons#coupon_codes'
      end
    end

    resources :coupon_codes, only: [:index, :new, :edit, :create, :update, :import] do
      collection do
        get 'approve_imported'
        get 'remove_imported'
        get 'export_modal'
        get 'export'
      end
    end

    resources :coupon_imports

    resources :coupon_code_imports, only: [:new, :create]

    resources :csv_exports, only: [:index, :edit, :destroy] do
      member do
        get 'rerun'
      end
    end

    resources :globals do
      collection do
        get 'export_modal'
        get 'export'
        get 'shop_mappings'
        post 'update_shop_mapping'
      end
    end

    resources :home, only: [:index]

    resources :media, only: [:index, :new, :edit, :create, :update]

    resources :options

    scope :quality do
      get 'active_coupons', to: 'quality#active_coupons'
      get 'http_links', to: 'quality#http_links'
      get 'invalid_urls', to: 'quality#invalid_urls'

      resources :expired_exclusives, only: [:index, :edit] do
        collection do
          get 'edit', to: 'expired_exclusives#edit', as: 'bulk_edit'
          post 'update', to: 'expired_exclusives#update', as: 'update'
        end
      end
    end

    resources :redirect_rules

    resources :settings, only: [:index, :update]

    patch :image_settings, to: 'settings#update_image_settings', as: :image_settings

    resources :shop_imports

    resources :shops, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
        get 'synch_keywords'
      end
    end

    resources :sites, only: [:index, :new, :edit, :create, :update]

    resources :snippets, only: [:index, :new, :edit, :create, :update]

    resources :static_pages, only: [:index, :new, :edit, :create, :update]

    resources :tags do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :tag_imports

    resources :templates, only: [:index]

    resources :tracking_clicks

    resources :tracking_users

    resources :translations do
      collection do
        get 'export_keys'
      end
    end

    resources :widgets

    resources :users, only: [:index, :new, :edit, :create, :update] do
      get '/current_site_id/:site_id', to: 'users#set_current_site_id'  , as: 'site_id'
      get '/unset_current_site_id'   , to: 'users#unset_current_site_id', as: 'unset_site_id'
    end
  end

  get '/index.php',       to: redirect('/')
  get '/index.php/*path', to: redirect{|params, request| "/#{params[:path]}#{ '.'+params[:format] if params[:format].present? }"}

  # FRONTEND ROUTES ARE LOADED DYNAMICALLY

  # DynamicRoutes.load_static_redirects

  DynamicRoutes.load

  # This is a fallback if no route can be matched and if not even the frontend controller is triggered to forward to a 404 page
  match "*path", to: "frontend#not_found", via: :all
  post "/", to: "frontend#not_found"
end

app/models/affiliate_network.rb
class AffiliateNetwork < ApplicationRecord
  include ActsAsStatusable
  has_statuses(
    active: 'active',
    blocked: 'blocked'
  )

  # Relations
  has_many :coupons

  # Validation
  validates_presence_of :name
  validates_uniqueness_of :name

  scope :active, -> { where(status: statuses[:active]) }

  def self.grid_filter(params)
    query = self
    query = query.where('1=1')
    query = query.where(id: params[:id]) if params[:id].present?
    query = query.where('name like ?', "%#{params[:name]}%") if params[:name].present?
    query = query.where('affiliate_networks.slug like ?', "%#{params[:slug]}%") if params[:slug].present?
    query = query.where(status: statuses[params[:status].to_sym]) if params[:status].present?
    query
  end
end

app/controllers/admin/affiliate_networks_controller.rb
require 'vue_data/affiliate_network'

module Admin
  class AffiliateNetworksController < BaseController
    before_action :authenticate_admin_user!
    load_and_authorize_resource

    before_action :set_affiliate_network, only: [:edit, :update]

    # GET /admin/affiliate_networks
    # GET /admin/affiliate_networks.json
    def index
      respond_to do |format|
        format.json { render json: VueData::AffiliateNetwork.render_json(AffiliateNetwork, params), status: :ok }
        format.html
      end
    end

    # GET /admin/affiliate_networks/new
    def new
      @affiliate_network = AffiliateNetwork.new
    end

    # GET /admin/affiliate_networks/1/edit
    def edit
    end

    # POST /admin/affiliate_networks
    # POST /admin/affiliate_networks.json
    def create
      @affiliate_network = AffiliateNetwork.new(affiliate_network_params)

      respond_to do |format|
        if @affiliate_network.save
          format.html { redirect_to admin_affiliate_networks_url, notice: 'Affiliate network was successfully created.' }
          format.json { render action: 'show', status: :created, location: admin_affiliate_networks_url }
        else
          format.html { render action: 'new' }
          format.json { render json: @affiliate_network.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/affiliate_networks/1
    # PATCH/PUT /admin/affiliate_networks/1.json
    def update
      respond_to do |format|
        if @affiliate_network.update(affiliate_network_params)
          format.html { redirect_to admin_affiliate_networks_url, notice: 'Affiliate network was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @affiliate_network.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_affiliate_network
      @affiliate_network = AffiliateNetwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliate_network_params
      params.require(:affiliate_network).permit(:name, :slug, :status, :validate_subid, :validation_regex)
    end
  end
end

app/views/admin/affiliate_networks/_form.html.erb
<div class="col-sm-12">

  <div class="box bordered-box blue-border">

    <div class="box-header blue-background">

      <div class="title">

        <i class="icon-group"></i>

        Affiliate Network Form

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @affiliate_network], html: {class: 'form form-horizontal', style: 'margin-bottom: 0'} do |f| %>

      <%= render partial: 'admin/shared/form_errors', locals: {ancestor: @affiliate_network} %>

      <div class="form-group <%= 'has-error' unless @affiliate_network.errors.messages[:name].blank? %>">

        <%= f.label :name, class: 'col-md-2 control-label' %>

        <div class="col-md-5">

          <%= f.text_field :name, class: 'form-control' %>

        </div>

      </div>

      <div class="form-group <%= 'has-error' unless @affiliate_network.errors.messages[:status].blank? %>">

        <%= f.label :status, class: 'col-md-2 control-label' %>

        <div class="col-md-5">

          <%= f.select :status, AffiliateNetwork.statuses, {}, { class: 'form-control', :disabled => @affiliate_network.new_record? } %>

        </div>

      </div>

      <div class="form-group <%= 'has-error' unless @affiliate_network.errors.messages[:slug].blank? %>">

        <%= f.label :slug, class: 'col-md-2 control-label' %>

        <div class="col-md-5">

          <%= f.text_field :slug, class: 'form-control', :disabled => !@affiliate_network.new_record? %>

        </div>

      </div>

      <div class="form-group <%= 'has-error' unless @affiliate_network.errors.messages[:validate_subid].blank? %>">

        <%= f.label :validate_subid, class: 'col-md-2 control-label' %>

        <div class="col-md-5">

          <%= f.check_box :validate_subid, class: 'form-control' %>

          <p class="help-block">

            <small>This validates for the subid parameter defined in the <%= link_to 'affiliate networks settings', admin_settings_path, target: '_blank' %>; the default parameter is: 'pctracking'</small>

          </p>

        </div>

      </div>

      <div class="form-group <%= 'has-error' unless @affiliate_network.errors.messages[:slug].blank? %>">

        <%= f.label :validation_regex, class: 'col-md-2 control-label' %>

        <div class="col-md-5">

          <%= f.text_field :validation_regex, class: 'form-control' %>

          <div class="help-small">

            Regex used to validate whether the coupon has a valid or invalid URL, or if the URL matches to the assigned Affiliate Network.

            Example: URL that starts with `https://www.awin1.com` and ends with `p=`

            <code>^https:\/\/www\.awin1\.com(.*)p=$</code>

          </div>

        </div>

      </div>


      <div class="form-actions form-actions-padding-sm">

        <div class="row">

          <div class="col-md-10 col-md-offset-2">

            <%= f.submit nil, class: 'btn btn-primary' if can? :create, AffiliateNetwork %>

            <%= link_to t('.cancel', :default => t('helpers.links.cancel')), admin_affiliate_networks_path, class: 'btn' %>

          </div>

        </div>

      </div>

      <% end %>

    </div>

  </div>

</div>


<script type="text/javascript">

document.ready = function(){

  <%- unless can? :manage, AffiliateNetwork -%>
    $("form.form-horizontal :input").attr("disabled", true);
  <%- end -%>
}

</script>

app/views/admin/affiliate_networks/edit.html.erb
<% model_class = AffiliateNetwork %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-group"></i>

        <span><%= t '.title', default: 'Edit %{model}', model: model_class.model_name.human.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li><%= model_class.model_name.human.pluralize.titleize %></li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active">Edit</li>

        </ul>

      </div>

    </div>

  </div>

</div>

<div class="row">

  <%= render :partial => 'admin/shared/flash' %>

</div>

<div class="row">

  <%= render partial: 'form', model_class: model_class %>

</div>

app/views/admin/affiliate_networks/index.html.erb
<% model_class = AffiliateNetwork %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-group"></i>

        <span><%= t '.title', default: model_class.model_name.human.pluralize.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active"><%= model_class.model_name.human.pluralize.titleize %></li>

        </ul>

      </div>

    </div>

  </div>

</div>

<%= render partial: 'admin/shared/flash' %>

<div class="box">

  <div class="box-content">

    <% if can? :create, model_class %>

      <div class="btn-toolbar">

        <%= link_to '<i class="icon-plus"></i> New Affiliate Network'.html_safe, new_admin_affiliate_network_path, class: 'btn btn-success' %>

      </div>

    <% end %>

    <div class="table-responsive">

      <div id="app"></div>

    </div>

  </div>

</div>

app/views/admin/affiliate_networks/new.html.erb
<% model_class = AffiliateNetwork %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-group"></i>

        <span><%= t '.title', default: 'New %{model}', model: model_class.model_name.human.titleize %></span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li><%= model_class.model_name.human.pluralize.titleize %></li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active">New</li>

        </ul>

      </div>

    </div>

  </div>

</div>

<div class="row">

  <%= render partial: 'admin/shared/flash' %>

</div>

<div class="row">

  <%= render partial: 'form' %>

</div>