config/routes.rb
require 'resque/server'

Frontend::Application.routes.draw do
  mount Api => '/api'

  root 'home#index'

  get '/admin',   to: redirect('pcadmin/home')
  get '/pcadmin', to: redirect('pcadmin/home')
  match '/admin/:name', to: redirect("pcadmin/%{name}"), via: [:get, :post]

  namespace :pcadmin, module: :admin, as: :admin do

    root 'home#index'

    match '/widgets/update_widget_area' => 'widgets#update_widget_area', via: [:get]
    match '/categories/change_status' => 'categories#change_status', via: [:get]
    match '/coupons/change_status' => 'coupons#change_status', via: [:get]
    match '/shops/change_status' => 'shops#change_status', via: [:get]
    match '/shops/order_coupons' => 'shops#order_coupons', via: [:get]
    match '/shops/update_coupon_order' => 'shops#update_coupon_order', via: [:get]
    match '/shops/import_template' => 'shops#import_template', via: [:get]
    match '/coupons/import_template' => 'coupons#import_template', via: [:get]
    match '/campaigns/import_template' => 'campaigns#import_template', via: [:get]
    match '/tags/import_template' => 'tags#import_template', via: [:get]
    match '/shops/update_shop_list_priority' => 'shops#update_shop_list_priority', via: [:post]
    match '/templates/save' => 'templates#save', via: [:post]
    match '/templates/get_layout' => 'templates#get_layout', via: [:get]
    match '/templates/restore_default' => 'templates#restore_default', via: [:get]
    match '/templates/delete_layout' => 'templates#delete_layout', via: [:delete]
    match '/caches' => 'caches#purge_url', via: [:post]
    match '/awin' => 'awin_migration#awin', via: [:get]
    match '/reload_routes' => 'settings#reload_routes', via: [:get]
    match '/migrate_awin' => 'awin_migration#migrate_awin', via: [:post]
    match '/shops/render_shops_select' => 'shops#render_shops_select', via: [:get]

    devise_for :users, class_name: 'User', controllers: {
      passwords:     'admin/passwords',
      registrations: 'admin/registrations',
      sessions:      'admin/sessions'
    }

    scope :users, as: :users do
      devise_scope :admin_user do
        post 'pre_sign_in', to: 'sessions#pre_sign_in'
      end
      resource :two_factors, only: [:create, :destroy], controller: 'users/two_factors'
    end

    authenticate do
      mount Resque::Server, :at => "/tasks"
    end

    resources :affiliate_networks, only: [:index, :new, :edit, :create, :update]

    resources :alerts, only: [:index, :destroy, :edit] do
      member do
        post 'mark_solved', to: 'alerts#mark_solved'
      end
    end

    resources :authors, only: [:index, :new, :edit, :create, :update]

    resources :banners

    resources :caches, only: [:index]

    resources :campaigns, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :campaign_imports

    resources :categories, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'order'
        post 'order', to: 'categories#update_order'
      end
    end

    resources :countries, only: [:index, :new, :edit, :create, :update]

    resources :coupons, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
      member do
        get 'coupon_codes', to: 'coupons#coupon_codes'
      end
    end

    resources :coupon_codes, only: [:index, :new, :edit, :create, :update, :import] do
      collection do
        get 'approve_imported'
        get 'remove_imported'
        get 'export_modal'
        get 'export'
      end
    end

    resources :coupon_imports

    resources :coupon_code_imports, only: [:new, :create]

    resources :csv_exports, only: [:index, :edit, :destroy] do
      member do
        get 'rerun'
      end
    end

    resources :globals do
      collection do
        get 'export_modal'
        get 'export'
        get 'shop_mappings'
        post 'update_shop_mapping'
      end
    end

    resources :home, only: [:index]

    resources :media, only: [:index, :new, :edit, :create, :update]

    resources :options

    scope :quality do
      get 'active_coupons', to: 'quality#active_coupons'
      get 'http_links', to: 'quality#http_links'
      get 'invalid_urls', to: 'quality#invalid_urls'

      resources :expired_exclusives, only: [:index, :edit] do
        collection do
          get 'edit', to: 'expired_exclusives#edit', as: 'bulk_edit'
          post 'update', to: 'expired_exclusives#update', as: 'update'
        end
      end
    end

    resources :redirect_rules

    resources :settings, only: [:index, :update]

    patch :image_settings, to: 'settings#update_image_settings', as: :image_settings

    resources :shop_imports

    resources :shops, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
        get 'synch_keywords'
      end
    end

    resources :sites, only: [:index, :new, :edit, :create, :update]

    resources :snippets, only: [:index, :new, :edit, :create, :update]

    resources :static_pages, only: [:index, :new, :edit, :create, :update]

    resources :tags do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :tag_imports

    resources :templates, only: [:index]

    resources :tracking_clicks

    resources :tracking_users

    resources :translations do
      collection do
        get 'export_keys'
      end
    end

    resources :widgets

    resources :users, only: [:index, :new, :edit, :create, :update] do
      get '/current_site_id/:site_id', to: 'users#set_current_site_id'  , as: 'site_id'
      get '/unset_current_site_id'   , to: 'users#unset_current_site_id', as: 'unset_site_id'
    end
  end

  get '/index.php',       to: redirect('/')
  get '/index.php/*path', to: redirect{|params, request| "/#{params[:path]}#{ '.'+params[:format] if params[:format].present? }"}

  # FRONTEND ROUTES ARE LOADED DYNAMICALLY

  # DynamicRoutes.load_static_redirects

  DynamicRoutes.load

  # This is a fallback if no route can be matched and if not even the frontend controller is triggered to forward to a 404 page
  match "*path", to: "frontend#not_found", via: :all
  post "/", to: "frontend#not_found"
end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < BaseController
    before_action :authenticate_admin_user!
    load_and_authorize_resource

    before_action :set_setting, only: [:index, :update]
    before_action :inform_settings_changed, only: [:update]
    before_action :set_last_setting_session, only: [:update]
    before_action :restore_defaults, only: [:update]

    after_action :purge_proxy_cache, only: [:update]

    def index
      set_dropdowns
      flash[:error] = 'Cache Settings Missing' unless @setting.caching.present?
      flash[:error] = 'Home Breadcrumb Name is missing in Site Settings' if @setting.home_breadcrumb_name_needed?
    end

    def update
      respond_to do |format|
        if @setting.update(setting_params)

          notice = if Setting.routes_changed
            'Route Settings were successfully saved. Home page cache was not cleared to avoid server overload.'
          else
            'Settings were successfully updated.'
          end

          format.html { redirect_to admin_settings_url, notice: notice }
        else
          set_dropdowns
          format.html { render action: 'index' }
        end
      end
    end

    def update_image_settings
      @image_setting = ImageSetting.find_or_create_by(site_id: Site.current.id)

      respond_to do |format|
        if @image_setting.update(image_setting_params)
          Setting.image_upload_changed = true
          format.html { redirect_to admin_settings_url, notice:  'Image Settings were successfully updated.' }
        else
          set_dropdowns
          format.html { render action: 'index' }
        end
      end
    end

    def reload_routes
      validate_super_admin
      head(:not_found) and return unless Site.current.present?

      RoutesChangedTimestamp.update_timestamp(Site.current)
      redirect_to admin_root_path, notice: "Routes for Site #{Site.current.hostname} are getting reloaded!"
    end

    private

    def purge_proxy_cache
      unless Setting.routes_changed
        CacheService.new(Site.current).purge(url_for(send("root_#{Site.current.id}_url")))
      end
    end

    def set_setting
      @setting = Setting.find_or_create_by(site_id: Site.current.id, campaign_id: nil)
      @image_setting = ImageSetting.find_or_create_by(site_id: Site.current.id)
    end

    def image_setting_params
      params.require(:image_setting).permit(
        :favicon,
        :remove_favicon,
        :logo,
        :remove_logo,
        :hero,
        :remove_hero,
        :see_more_categories_background,
        :remove_see_more_categories_background
      )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.permit(
        style: [
          :styles_enabled,
          :theme,
          :fallback_theme,
          :color_text,
          :color_headline,
          :color_cloud,
          :color_ready,
          :color_sky,
          :color_royal,
          :color_freedom,
          :color_brand_primary,
          :color_brand_secondary,
          :color_brand_tertiary,
          :color_brand_quaternary,
          :header_bg_color,
          :header_font_color_primary,
          :main_bg_color,
          :main_box_border_color,
          :main_font_color_primary,
          :main_font_color_secondary,
          :main_font_color_tertiary,
          :main_text_link_color,
          :footer_bg_footer,
          :footer_font_color_primary,
          :footer_font_color_secondary,
          :font_family_base,
          :font_family_h1,
          :font_family_h2,
          :font_family_h3,
          :font_family_h4
        ],
        publisher_site: [
          :show_home_link,
          :home_breadcrumb_name,
          :blog_link_title,
          :blog_link_url,
          :external_logo_url,
          :external_logo_rel_attr,
          :allow_coupon_bookmarks,
          :show_news_popup_for_empty_shop,
          :show_disclaimer,
          :disclaimer_text,
          :show_footer,
          :wls_footer_style,
          :show_social_media_column,
          :currency_symbol_position,
          :days_coupon_is_new,
          :shop_pages_title_structure,
          :inline_newsletter_position,
          :hide_coupons_of_sub_pages,
          :show_prominent_search_on_homepage,
          :twitter_site,
          :facebook_site,
          :facebook_app_id,
          :facebook_admin_ids,
          :show_fb_comments,
          :show_topbar,
          :show_crosslinks,
          :open_graph_image,
          :hide_star_rating,
          :hide_expired_coupons,
          :paginate_categories,
          :unpaginate_coupons_count,
          :summary_widget,
          :secondary_summary_widget,
          :reduced_js_features,
          :hero_links,
          :anchors_for_summary_widget,
          navigation_shop_ids: [],
          summary_shop_ids: [],
          premium_summary_shop_ids: [],
          footer_shop_ids: [],
          footer_campaign_ids: [],
          featured_shop_ids: []
        ],
        routes: [
          :application_root_dir,
          :page_show,
          :category,
          :category_show,
          :subcategory_show,
          :go_to_coupon,
          :popular_coupons,
          :top_coupons,
          :new_coupons,
          :expiring_coupons,
          :free_delivery_coupons,
          :free_coupons,
          :exclusive_coupons,
          :campaign_page,
          :campaign_sub_page,
          :shop_campaign_page,
          :search_page,
          :shop_index,
          :shop_show,
          :contact_form,
          :partner_form,
          :report_form
        ],
        legal_pages: [
          :about_us_url,
          :imprint_url,
          :terms_and_conditions_url,
          :privacy_policy_url,
          :press_url,
          :cookie_policy_url,
          :faq_url
        ],
        newsletter: [
          :newsletter_enabled,
          :mailchimp_api_key,
          :mailchimp_list_id
        ],
        homepage: [
          :title,
          :meta_title,
          :meta_description,
          :meta_robots,
          :head_scripts,
          search_box_shops: [],
          search_box_shops_popular: []
        ],
        admin_rules: [
          :canonical_domain,
          :dynamic_pages,
          :static_pages,
          :robots_txt,
          :cookie_policy_url
        ],
        mail_forms: [
          :contact_emails,
          :contact_form_enabled,
          :partner_form_enabled,
          :report_form_enabled
        ],
        caching: [
          :proxy_server_type,
          :fastly_auth_key,
          :fastly_service_id,
          :fastly_cache_purge_host,
          :use_surrogate_keys,
          :cloudflare_zone_id
        ],
        visibility: [
          :coupon_properties,
          :coupon_description,
          :site_header,
          :shop_header
        ],
        tracking: [
          :google_analytics_id,
          :google_tag_manager_id,
          :client_google_tag_manager_id,
          :head_scripts,
          :body_scripts
        ],
        banner: [
          :theme,
          :caption_heading,
          :caption_body,
          :default_banner_img_url,
          :default_banner_logo_url,
          :default_banner_font_color,
          :default_banner_cta_background,
          :default_banner_cta_color,
          :button_text,
          :start_date,
          :end_date,
          :countdown_date,
          :show_banner,
          :target_url
        ],
        shop_banner: [
          :show_banner,
          :image_url,
          :target_url,
          :show_banner,
          :target_url,
          excluded_shop_ids: []
        ],
        alert: [
          :uniq_coupons_threshold
        ],
        menu: [
          :show_home_link,
          :show_categories,
          :show_coupons,
          :show_campaigns,
          navigation_shop_ids: [],
          navigation_category_ids: [],
          main_shop_ids: [],
          main_campaign_ids: [],
          footer_shop_ids: [],
          footer_campaign_ids: []
        ],
        experimental: [
          :flyout_style,
          shops_with_elevated_coupons: [],
          shops_with_flyout_coupon: []
        ]
      )
    end

    def set_dropdowns
      shops = Site.current.shops.active
      campaigns = Site.current.campaigns.active
      categories = Site.current.categories.active

      @featured_shop_ids_collection = shops.order_by_set(@setting.publisher_site.try(:featured_shop_ids)).collect { |i| [i.title_and_site_name, i.id] }
      @navigation_shop_ids_collection = shops.order_by_set(@setting.menu.try(:navigation_shop_ids)).collect { |i| [i.title_and_site_name, i.id] }
      @navigation_category_ids_collection = categories.order_by_set(@setting.menu.try(:navigation_category_ids)).collect { |i| [i.name, i.id] }
      @main_shop_ids_collection = shops.order_by_set(@setting.menu.try(:main_shop_ids)).collect { |i| [i.title_and_site_name, i.id] }
      @main_campaign_ids_collection = campaigns.active.order_by_set(@setting.menu.try(:main_campaign_ids)).collect { |i| [i.id_and_nav_title_or_name, i.id] }
      @search_box_shops_collection = shops.order_by_set(@setting.menu.try(:search_box_shops)).collect { |i| [i.title_and_site_name, i.id] }
      @search_box_shops_popular_collection = shops.order_by_set(@setting.menu.try(:search_box_shops_popular)).collect { |i| [i.title_and_site_name, i.id] }
      @footer_shop_ids_collection = shops.order_by_set(@setting.menu.try(:footer_shop_ids)).collect { |i| [i.title_and_site_name, i.id] }
      @footer_campaign_ids_collection = campaigns.order_by_set(@setting.menu.try(:footer_campaign_ids)).collect { |i| [i.id_and_nav_title_or_name, i.id] }
      @excluded_shop_ids_collection = Site.current.shops.order_by_set(@setting.shop_banner.try(:excluded_shop_ids)).collect { |i| [i.title_and_site_name, i.id] }

app/views/admin/settings/_default_status.html.erb
<div class="col-sm-12 col-md-6" id="default-status">

  <div class="box bordered-box blue-border <%= 'box-collapsed' unless session[:last_setting] == 'default_status' %>">

    <div class="box-header green-background">

      <div class="title">

        <i class="icon-ok-sign"></i>

        Default Status

      </div>

      <div class="actions">

        <a class="btn box-collapse btn-xs btn-link" href="#">

          <i></i>

        </a>

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @setting], method: :patch, html: {class: 'form form-horizontal', style: 'margin-bottom: 0'} do |f| %>

        <%= hidden_field_tag :option_type, 'default_status' %>

        <%= fields_for :default_status, @setting.default_status do |ff| %>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :coupon %>

              <%= ff.select :coupon, Status.to_select, {prompt: true}, {class: 'form-control'} %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :shop %>

              <%= ff.select :shop, Status.to_select, {prompt: true}, {class: 'form-control text_field'} %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :category %>

              <%= ff.select :category, Status.to_select, {prompt: true}, {class: 'form-control text_field'} %>

            </div>

          </div>

          <div class="form-actions form-actions-padding-sm">

            <div class="row">

              <div class="col-md-2">

                <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

              </div>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/settings/_experimental.html.erb
<div class="col-sm-12 col-md-6" id="admin-rules">

  <div class="box box-bordered red-border <%= 'box-collapsed' unless session[:last_setting] == 'alert' %>">

    <div class="box-header white-background">

      <div class="title">

        <i class="icon-question"></i>

        Experimental

      </div>

      <div class="actions">

        <a class="btn box-collapse btn-xs btn-link" href="#">

          <i></i>

        </a>

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @setting], method: :patch, html: {class: 'form form-horizontal', style: 'margin-bottom: 0'} do |f| %>

        <%= hidden_field_tag :option_type, 'experimental' %>

        <%= fields_for :experimental , @setting.experimental do |ff| %>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :shops_with_elevated_coupons %>

              <%= ff.select :shops_with_elevated_coupons, @shops_with_elevated_coupons_collection, { prompt: true }, { class: 'select2 form-control', multiple: true } %>

              <div class="help-box"><small>Changes Coupon Headings from h3 to h2 on selected shops</small></div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :shops_with_flyout_coupon %>

              <%= ff.select :shops_with_flyout_coupon, @shops_with_flyout_coupon_collection, { prompt: true }, { class: 'select2 form-control', multiple: true } %>

              <div class="help-box"><small>Adds flyout coupon notification to shop page</small></div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :flyout_style %>

              <%= ff.select :flyout_style, @flyout_style_options, { :selected => ff.object.present? ? (ff.object.flyout_style || '') : '' }, class: 'form-control' %>

            </div>

          </div>

          <div class="form-actions form-actions-padding-sm">

            <div class="row">

              <div class="col-md-2">

                <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

              </div>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/settings/_homepage.html.erb
<div class="col-sm-12 col-md-6" id="homepage">

  <div class="box bordered-box blue-border <%= 'box-collapsed' unless session[:last_setting] == 'homepage' %>">

    <div class="box-header fb-background">

      <div class="title">

        <i class="icon-home"></i>

        Homepage Settings

      </div>

      <div class="actions">

        <a class="btn box-collapse btn-xs btn-link" href="#">

          <i></i>

        </a>

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @setting], method: :patch, html: { class: 'form form-horizontal', style: 'margin-bottom: 0' } do |f| %>

        <%= hidden_field_tag :option_type, 'homepage' %>

        <%= fields_for :homepage, @setting.homepage do |ff| %>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :title %>

              <%= ff.text_field :title, class: 'form-control', pattern: ".{0,70}", title: 'Maximum 70 characters' %>

              <div class="help-block">

                <small>Maximum 70 characters</small>

              </div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :meta_title %>

              <%= ff.text_field :meta_title, class: 'form-control', pattern: ".{0,70}", title: 'Maximum 70 characters' %>

              <div class="help-block">

                <small>Maximum 70 characters</small>

              </div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :meta_description %>

              <%= ff.text_field :meta_description, class: 'form-control', pattern: ".{0,160}", title: 'Maximum 160 characters' %>

              <div class="help-block">

                <small>Maximum 160 characters</small>

              </div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :meta_description %>

              <%= ff.select :meta_robots, Option::get_select_options('robots', true), { include_blank: true }, { class: 'form-control' } %>

              <div class="help-block">

                <small>If the "Admin Rules" say "noindex, nofollow" then the page will not be indexed, even if you set
                  'index,follow' above. Otherwise you can choose if you want to index this page or not.
                </small>

              </div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :head_scripts %>

              <%= ff.text_area :head_scripts, class: 'form-control' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label "SearchBox placeholder shops" %>

              <%= ff.select :search_box_shops, @search_box_shops_collection, { include_hidden: false }, { class: 'form-control', multiple: true, id: "search_box_shops" } %>

              <div class="help-block">

                <small>3 shops maximum</small>

              </div>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label "SearchBox Shops popular" %>

              <%= ff.select :search_box_shops_popular, @search_box_shops_popular_collection, { include_hidden: false }, { class: 'form-control', multiple: true, id: "search_box_shops_popular" } %>

              <div class="help-block">

                <small>8 shops maximum</small>

              </div>

            </div>

          </div>

          <div class="form-actions form-actions-padding-sm">

            <div class="row">

              <div class="col-md-2">

                <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

              </div>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/settings/_image_upload.html.erb
<div class="col-sm-12 col-md-6" id="image-upload">

  <div class="box bordered-box muted-border <%= 'box-collapsed' unless session[:last_setting] == 'image_upload' %>">

    <div class="box-header muted-background">

      <div class="title">

        <i class="icon-upload-alt"></i>

        Image Upload

      </div>

      <div class="actions">

        <a class="btn box-collapse btn-xs btn-link" href="#">

          <i></i>

        </a>

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @image_setting], url: admin_image_settings_path, method: :patch, html: { class: 'form form-horizontal', style: 'margin-bottom: 0', multipart: true } do |f| %>

        <div class="form-group">

          <div class="col-sm-12">

            <%= f.label :favicon %>

              <br />

              <% if  @image_setting.favicon.present? %>

                <%= image_tag @image_setting.favicon_url, width: '50' %>

                <p>

                  <label>

                    <%= f.check_box :remove_favicon %>

                    Remove favicon

                  </label>

                </p>

              <% end %>

            <%= f.file_field :favicon, :class => 'form-control' %>

          </div>

        </div>

        <div class="form-group">

          <div class="col-sm-12">

            <%= f.label :logo %>

              <br />

              <% if  @image_setting.logo.present? %>

                <%= image_tag @image_setting.logo_url, width: '150' %>

                <p>

                  <label>

                    <%= f.check_box :remove_logo %>

                    Remove logo

                  </label>

                </p>

              <% end %>

            <%= f.file_field :logo, :class => 'form-control' %>

          </div>

        </div>

        <div class="form-group">

          <div class="col-sm-12">

            <%= f.label :hero %>

              <br />

              <% if  @image_setting.hero.present? %>

                <%= image_tag @image_setting.hero_url, width: '150' %>

                <p>

                  <label>

                    <%= f.check_box :remove_hero %>

                    Remove hero

                  </label>

                </p>

              <% end %>

            <%= f.file_field :hero, :class => 'form-control' %>

          </div>

        </div>

        <hr>

        <h3>Theme Options: Simple 2019</h3>

        <div class="form-group">

          <div class="col-sm-12">

            <%= f.label :see_more_categories_background %>

              <br />

              <% if  @image_setting.see_more_categories_background.present? %>

                <%= image_tag @image_setting.see_more_categories_background_url, width: '150' %>

                <p>

                  <label>

                    <%= f.check_box :remove_see_more_categories_background %>

                    Remove "see more categories" background

                  </label>

                </p>

              <% end %>

            <%= f.file_field :see_more_categories_background, :class => 'form-control' %>

          </div>

        </div>

        <div class="form-actions form-actions-padding-sm">

          <div class="row">

            <div class="col-md-2">

              <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

            </div>

          </div>

        </div>

      <%- end -%>

    </div>

  </div>

</div>

app/views/admin/settings/_legal_pages.html.erb
<div class="col-sm-12 col-md-6" id="legal-pages">

  <div class="box bordered-box blue-border <%= 'box-collapsed' unless session[:last_setting] == 'legal_pages' %>">

    <div class="box-header banana-background">

      <div class="title">

        <i class="icon-legal"></i>

        Legal Pages Settings

      </div>

      <div class="actions">

        <a class="btn box-collapse btn-xs btn-link" href="#">

          <i></i>

        </a>

      </div>

    </div>

    <div class="box-content">

      <%= form_for [:admin, @setting], method: :patch, html: {class: 'form form-horizontal', style: 'margin-bottom: 0'} do |f| %>

        <%= hidden_field_tag :option_type, 'legal_pages' %>

        <%= fields_for :legal_pages, @setting.legal_pages do |ff| %>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :about_us_url %>

              <%= ff.text_field :about_us_url, class: 'form-control', placeholder: 'e.g. /about-us' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :imprint_url %>

              <%= ff.text_field :imprint_url, class: 'form-control', placeholder: 'e.g. /imprint' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :terms_and_conditions_url %>

              <%= ff.text_field :terms_and_conditions_url, class: 'form-control', placeholder: 'e.g. /terms-and-conditions' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :privacy_policy_url %>

              <%= ff.text_field :privacy_policy_url, class: 'form-control', placeholder: 'e.g. /data-security' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :cookie_policy_url %>

              <%= ff.text_field :cookie_policy_url, class: 'form-control', placeholder: 'e.g. /cookie-policy' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :press_url %>

              <%= ff.text_field :press_url, class: 'form-control', placeholder: 'e.g. /press' %>

            </div>

          </div>

          <div class="form-group">

            <div class="col-sm-12">

              <%= ff.label :faq_url %>

              <%= ff.text_field :faq_url, class: 'form-control', placeholder: 'e.g. /faq' %>

            </div>

          </div>

          <div class="form-actions form-actions-padding-sm">

            <div class="row">

              <div class="col-md-2">

                <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

              </div>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>

  </div>

</div>