config/routes.rb
require 'resque/server'

Frontend::Application.routes.draw do
  mount Api => '/api'

  root 'home#index'

  get '/admin',   to: redirect('pcadmin/home')
  get '/pcadmin', to: redirect('pcadmin/home')
  match '/admin/:name', to: redirect("pcadmin/%{name}"), via: [:get, :post]

  namespace :pcadmin, module: :admin, as: :admin do

    root 'home#index'

    match '/widgets/update_widget_area' => 'widgets#update_widget_area', via: [:get]
    match '/categories/change_status' => 'categories#change_status', via: [:get]
    match '/coupons/change_status' => 'coupons#change_status', via: [:get]
    match '/shops/change_status' => 'shops#change_status', via: [:get]
    match '/shops/order_coupons' => 'shops#order_coupons', via: [:get]
    match '/shops/update_coupon_order' => 'shops#update_coupon_order', via: [:get]
    match '/shops/import_template' => 'shops#import_template', via: [:get]
    match '/coupons/import_template' => 'coupons#import_template', via: [:get]
    match '/campaigns/import_template' => 'campaigns#import_template', via: [:get]
    match '/tags/import_template' => 'tags#import_template', via: [:get]
    match '/shops/update_shop_list_priority' => 'shops#update_shop_list_priority', via: [:post]
    match '/templates/save' => 'templates#save', via: [:post]
    match '/templates/get_layout' => 'templates#get_layout', via: [:get]
    match '/templates/restore_default' => 'templates#restore_default', via: [:get]
    match '/templates/delete_layout' => 'templates#delete_layout', via: [:delete]
    match '/caches' => 'caches#purge_url', via: [:post]
    match '/awin' => 'awin_migration#awin', via: [:get]
    match '/reload_routes' => 'settings#reload_routes', via: [:get]
    match '/migrate_awin' => 'awin_migration#migrate_awin', via: [:post]
    match '/shops/render_shops_select' => 'shops#render_shops_select', via: [:get]

    devise_for :users, class_name: 'User', controllers: {
      passwords:     'admin/passwords',
      registrations: 'admin/registrations',
      sessions:      'admin/sessions'
    }

    scope :users, as: :users do
      devise_scope :admin_user do
        post 'pre_sign_in', to: 'sessions#pre_sign_in'
      end
      resource :two_factors, only: [:create, :destroy], controller: 'users/two_factors'
    end

    authenticate do
      mount Resque::Server, :at => "/tasks"
    end

    resources :affiliate_networks, only: [:index, :new, :edit, :create, :update]

    resources :alerts, only: [:index, :destroy, :edit] do
      member do
        post 'mark_solved', to: 'alerts#mark_solved'
      end
    end

    resources :authors, only: [:index, :new, :edit, :create, :update]

    resources :banners

    resources :caches, only: [:index]

    resources :campaigns, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :campaign_imports

    resources :categories, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'order'
        post 'order', to: 'categories#update_order'
      end
    end

    resources :countries, only: [:index, :new, :edit, :create, :update]

    resources :coupons, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
      end
      member do
        get 'coupon_codes', to: 'coupons#coupon_codes'
      end
    end

    resources :coupon_codes, only: [:index, :new, :edit, :create, :update, :import] do
      collection do
        get 'approve_imported'
        get 'remove_imported'
        get 'export_modal'
        get 'export'
      end
    end

    resources :coupon_imports

    resources :coupon_code_imports, only: [:new, :create]

    resources :csv_exports, only: [:index, :edit, :destroy] do
      member do
        get 'rerun'
      end
    end

    resources :globals do
      collection do
        get 'export_modal'
        get 'export'
        get 'shop_mappings'
        post 'update_shop_mapping'
      end
    end

    resources :home, only: [:index]

    resources :media, only: [:index, :new, :edit, :create, :update]

    resources :options

    scope :quality do
      get 'active_coupons', to: 'quality#active_coupons'
      get 'http_links', to: 'quality#http_links'
      get 'invalid_urls', to: 'quality#invalid_urls'

      resources :expired_exclusives, only: [:index, :edit] do
        collection do
          get 'edit', to: 'expired_exclusives#edit', as: 'bulk_edit'
          post 'update', to: 'expired_exclusives#update', as: 'update'
        end
      end
    end

    resources :redirect_rules

    resources :settings, only: [:index, :update]

    patch :image_settings, to: 'settings#update_image_settings', as: :image_settings

    resources :shop_imports

    resources :shops, only: [:index, :new, :edit, :create, :update] do
      collection do
        get 'export_modal'
        get 'export'
        get 'synch_keywords'
      end
    end

    resources :sites, only: [:index, :new, :edit, :create, :update]

    resources :snippets, only: [:index, :new, :edit, :create, :update]

    resources :static_pages, only: [:index, :new, :edit, :create, :update]

    resources :tags do
      collection do
        get 'export_modal'
        get 'export'
      end
    end

    resources :tag_imports

    resources :templates, only: [:index]

    resources :tracking_clicks

    resources :tracking_users

    resources :translations do
      collection do
        get 'export_keys'
      end
    end

    resources :widgets

    resources :users, only: [:index, :new, :edit, :create, :update] do
      get '/current_site_id/:site_id', to: 'users#set_current_site_id'  , as: 'site_id'
      get '/unset_current_site_id'   , to: 'users#unset_current_site_id', as: 'unset_site_id'
    end
  end

  get '/index.php',       to: redirect('/')
  get '/index.php/*path', to: redirect{|params, request| "/#{params[:path]}#{ '.'+params[:format] if params[:format].present? }"}

  # FRONTEND ROUTES ARE LOADED DYNAMICALLY

  # DynamicRoutes.load_static_redirects

  DynamicRoutes.load

  # This is a fallback if no route can be matched and if not even the frontend controller is triggered to forward to a 404 page
  match "*path", to: "frontend#not_found", via: :all
  post "/", to: "frontend#not_found"
end

app/models/csv_export.rb
class CsvExport < ApplicationRecord

  belongs_to :user

  serialize :params
  serialize :error_messages

  mount_uploader :file, Admin::JobFileUploader

  # used for migration with zero downtime. disables writes to the rejected colums
  def self.columns
    super.reject { |column| ['site_id'].include?(column.name) }
  end

  def self.grid_filter(params)
    query = self
    query = query.where('1=1')
    query = query.where(user: User.current.allowed_active_users_of(self, true)) if User.current.present?
    query = query.where(id: params[:id]) if params[:id].present?
    query = query.where(export_type: params[:export_type]) if params[:export_type].present?
    query = query.where(status: params[:status]) if params[:status].present?
    query = query.where(user: params[:user]) if params[:user].present?
    query = query.where('created_at >= ?', params['created_at_from']) if params['created_at_from'].present?
    query = query.where('created_at <= ?', params['created_at_to']) if params['created_at_to'].present?
    query = query.where('last_executed >= ?', params['last_executed_from']) if params['last_executed_from'].present?
    query = query.where('last_executed <= ?', params['last_executed_to']) if params['last_executed_to'].present?
    query
  end

  def self.grid_filter_dropdowns
    h = {}
    h[:user] = User.current.allowed_active_users_of(self, true).map do |user|
      { user.id => user.full_name }
    end
    h[:user].insert(0, {'' => 'all'})
    h
  end

  def exportable
    self.export_type.classify.constantize
  end

  def open?
    self.status == 'pending' || self.status == 'running'
  end

  def run_export
    exportable.export(self.params)
  end

  def site
    raise "Invalid call of 'site' in coupon_imports.rb; Site is not a relation of csv_export anymore; Please inform admin."
  end

  def site_id
    raise "Invalid call of 'site_id' in coupon_imports.rb; Site is not a relation of csv_export anymore; Please inform admin."
  end

  def sanitized_params_string
    return '' unless params.present?
    string = ''
    params.each do |k, v|
      if v.present? && [*v].reject(&:blank?).present?
        if ['shop_id', 'shop_ids'].include?(k)
          string += '<b>Shops</b>: ' + Shop.where(id: v).pluck(:slug).join(', ') + '<br />'
        else
          string += "<b>#{k.to_s.titleize}</b>: #{[*v].reject(&:blank?).join(', ')}<br />"
        end
      end
    end
    string
  end
end

app/controllers/admin/csv_exports_controller.rb
require 'vue_data/csv_export'

module Admin
  class CsvExportsController < BaseController
    before_action :authenticate_admin_user!
    before_action :get_csv_export, only: [:edit, :destroy, :rerun]

    def index
      respond_to do |format|
        format.html
        format.json { render json: ::VueData::CsvExport.render_json(nil, params), status: :ok }
      end
    end

    def edit
    end

    def destroy
      @admin_csv_export.destroy
      respond_to do |format|
        format.json { head :ok }
      end
    end

    def rerun
      @admin_csv_export.user_id = User.current.id
      @admin_csv_export.status  = 'pending'
      @admin_csv_export.remove_file!

      respond_to do |format|
        if @admin_csv_export.save
          Resque.enqueue(CsvExportWorker, @admin_csv_export.id)
          format.html { redirect_to admin_csv_exports_path, notice: 'File is beeing processed again' }
        else
          @admin_csv_export.update_attribute(:status, 'error')
          @admin_csv_export.update_attribute(:error_messages, @admin_csv_export.errors.full_messages)
          redirect_to 'index', notice: 'Error while processing the requested file'
        end
      end
    end

  private

    def get_csv_export
      @admin_csv_export = CsvExport.find(params[:id])
    end

  end
end

app/views/admin/csv_exports/edit.html.erb
<%- model_class = CsvExport -%>
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-tags"></i>
        <span>XLS Export</span>
      </h1>

      <!-- breadcrumbs -->
      <div class="pull-right">
        <ul class="breadcrumb">
          <li>
            <a href="/pcadmin">
              <i class="icon-tags"></i>
            </a>
          </li>
          <li class="separator">
            <i class="icon-angle-right"></i>
          </li>
          <li class="active">XLS Export</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= render :partial => 'admin/shared/flash' %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @admin_csv_export.user.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= @admin_csv_export.file_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @admin_csv_export.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:export_type) %>:</strong></dt>
  <dd><%= @admin_csv_export.export_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:params) %>:</strong></dt>
  <dd><%= @admin_csv_export.params %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @admin_csv_export.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_executed) %>:</strong></dt>
  <dd><%= @admin_csv_export.last_executed %></dd>
  <%- if @admin_csv_export.error_messages.present? -%>
    <dt><strong><%= model_class.human_attribute_name(:error_messages) %>:</strong></dt>
    <dd>
      <ul>
        <%- if @admin_csv_export.error_messages.is_a?(String) -%>
          <li><%= @admin_csv_export.error_messages %></li>
        <%- end -%>
        <%- @admin_csv_export.error_messages.each do |message| -%>
          <li><%= message %></li>
        <%- end if @admin_csv_export.error_messages.is_a?(Array)-%>
      </ul>
    </dd>
  <%- end -%>
  <%- if @admin_csv_export.file_url.present? -%>
    <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
    <dd><%= link_to 'Download', @admin_csv_export.file_url, target: '_blank' %></dd>
  <%- end -%>
</dl>

<div class="form-actions">

  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_csv_exports_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_csv_export_path(@admin_csv_export),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

  <% unless @admin_csv_export.open? %>
    <%= link_to('<i class="icon-refresh"></i>'.html_safe, rerun_admin_csv_export_path(@admin_csv_export), class: 'btn', title: 'Run Export Again') %>
  <% end %>
</div>

app/views/admin/csv_exports/index.html.erb
<% model_class = CsvExport %>

<div class="row">

  <div class="col-xs-12">

    <div class="page-header">

      <h1 class="pull-left">

        <i class="icon-pencil"></i>

        <span>XLS Exports</span>

      </h1>

      <div class="pull-right">

        <ul class="breadcrumb">

          <li>

            <a href="/pcadmin">

              <i class="icon-home"></i>

            </a>

          </li>

          <li class="separator">

            <i class="icon-angle-right"></i>

          </li>

          <li class="active">XLS Exports</li>

        </ul>

      </div>

    </div>

  </div>

</div>

<%= render partial: 'admin/shared/flash' %>

<div class="box">

  <div class="box-content">

    <div class="table-responsive">

      <div id="app"></div>

    </div>

  </div>

</div>